name: Upload artifact
description: Upload an encrypted zip archive as a github artifact.

inputs:
  path:
    description: 'The path(s) that should be uploaded. Paths may contain globs. Only the final component of a path is uploaded.'
    required: true
  name:
    description: 'The name of the artifact.'
    required: true
  retention-days:
    description: 'How long the artifact should be retained for.'
    default: 60
  encryptionSecret:
    description: 'The secret to use for encrypting the files.'
    required: true
  overwrite:
    description: 'Overwrite an artifact with the same name.'
    default: false
    required: false

runs:
  using: "composite"
  steps:
    - name: Install zip
      uses: ./.github/actions/setup_bazel_nix
      with:
        nixTools: |
          zip

    - name: Create temporary directory
      id: tempdir
      shell: bash
      run: echo "directory=$(mktemp -d)" >> "$GITHUB_OUTPUT"
